name: annelik
description: firstVer


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.2.3+1
  intl_phone_number_input: ^0.7.0+2
  image_size_getter: ^2.1.1
  pinput: ^2.2.11
  custom_navigation_bar: ^0.8.2
  get: ^4.6.5
  percent_indicator: ^4.2.2
  flutter_holo_date_picker: ^1.0.3
  shimmer: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: any



flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_gravity: fill

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
          style: italic
  assets:
    - assets/profilebar/notification.png
    - assets/profilebar/find.png
    - assets/icon/icon.png
    - assets/icon/detailicon.png
    - assets/icon/topbackbutton.png
    - assets/requestsms/getsmsbutton.png
    - assets/loginscreen/image.png
    - assets/loginscreen/login.png
    - assets/loginscreen/register.png
    - assets/loginscreen/text.png
    - assets/loginscreen/contractimage.png
    - assets/requestsms/text.png
    - assets/requestsms/numbertextbox.png
    - assets/splash/splash.png
    - assets/onboardScreen/onboard1/image.png
    - assets/onboardScreen/onboard1/button.png
    - assets/onboardScreen/onboard1/subtract.png
    - assets/onboardScreen/onboard2/image.png
    - assets/onboardScreen/onboard2/button.png
    - assets/onboardScreen/onboard2/subtract.png
    - assets/onboardScreen/onboard3/image.png
    - assets/onboardScreen/onboard3/button.png
    - assets/onboardScreen/onboard3/subtract.png
    - assets/bottomnavigationbar/home.png
    - assets/bottomnavigationbar/blog.png
    - assets/bottomnavigationbar/forum.png
    - assets/bottomnavigationbar/more.png
    - assets/avatars/1.png
    - assets/avatars/2.png
    - assets/avatars/3.png
    - assets/avatars/4.png
    - assets/avatars/5.png
    - assets/avatars/6.png
    - assets/avatars/7.png
    - assets/avatars/8.png
    - assets/avatars/9.png
    - assets/otherpage/alisverislistesi.png
    - assets/otherpage/bebekisimleri.png
    - assets/otherpage/bizidegerlendir.png
    - assets/otherpage/geribildirim.png
    - assets/otherpage/hastahanecantasi.png
    - assets/otherpage/kasilmasayar.png
    - assets/otherpage/kaydedilenler.png
    - assets/otherpage/profile.png